# Example Streamlit secrets.toml file for TariffDoc AI

# OpenAI API configuration
[openai]
OPENAI_API_KEY = "sk-your-openai-api-key-here"
OPENAI_MODEL = "gpt-4"

# Note: In Streamlit Cloud, you would enter these values in the "Secrets" section
# of your app's settings. The format would be exactly as shown above.
# Streamlit will automatically make these values available to your app as:
# st.secrets["openai"]["OPENAI_API_KEY"] and st.secrets["openai"]["OPENAI_MODEL"]
